const assert=require('node:assert/strict'),fs=require('node:fs');
const {Solver,defaults,validate}=require('../../ios-web/dist/solver.js');
let c=defaults();c.across=8;c.end=60;c.flipTimes=[17.123,40.987];let s=new Solver(c);for(const t of [17.123,40.987,60])s.advanceTo(t,10000);
const data=fs.readFileSync('build/ios-tests/reference.bin');assert.equal(data.readInt32BE(0),s.size);let offset=4,max=0;for(const v of [...s.temperatures(),...s.surfaceTemperatures(),s.panPower,s.airPower,s.boxEnergy]){max=Math.max(max,Math.abs(v-data.readDoubleBE(offset)));offset+=8;}assert.equal(offset,data.length);assert(max<1e-8);console.log('Java/JavaScript full-field + surface + powers + energy max absolute difference:',max);
c=defaults();c.end=50;c.across=8;c.flipTimes=[17.123,40.987];s=new Solver(c);let no=new Solver({...c,flipTimes:[]});s.advanceTo(17.123,10000);no.advanceTo(17.123,10000);assert.deepEqual(s.u,no.u);assert.equal(s.flipsAt(s.time),1);s.advanceTo(40.987,10000);assert.equal(s.flipsAt(s.time),2);assert(Math.abs(s.energyBalanceError())<1e-6);
c=defaults();c.across=8;c.end=20;c.panTemperature=c.airTemperature=37;s=new Solver(c);s.initializeUniform(37);s.advanceTo(20,10000);assert(Math.abs(s.coreStats()[0]-37)<1e-8);assert(Math.abs(s.coreStats()[1]-37)<1e-8);
function roots(bi){return Array.from({length:60},(_,n)=>{let a=n*Math.PI+1e-9,b=(n+1)*Math.PI-1e-9;for(let j=0;j<80;j++){const m=(a+b)/2;if(1-m/Math.tan(m)-bi>0)b=m;else a=m;}return(a+b)/2;});}
for(const bi of [.1,1,10]){c={...defaults(),length:.04,width:.04,thickness:.04,exponent:2,asymmetry:0,across:12,k:1,rho:1,cp:1,initial:0,airTemperature:1,airH:bi/.02,contactDepth:0,flipTimes:[],end:.00004};s=new Solver(c);s.advanceTo(c.end,10000);let error=0,count=0;const f=s.temperatures(),lambdas=roots(bi);for(const i of s.coreIndices){const r=Math.sqrt(s.x(i%s.nx)**2+s.y(Math.floor(i/s.nx)%s.ny)**2+s.z(Math.floor(i/(s.nx*s.ny)))**2);if(r>.01)continue;let theta=0;for(const l of lambdas){const v=l*r/.02;theta+=4*(Math.sin(l)-l*Math.cos(l))/(2*l-Math.sin(2*l))*(v===0?1:Math.sin(v)/v)*Math.exp(-l*l*.1);}error+=(f[i]-(1-theta))**2;count++;}const rms=Math.sqrt(error/count);assert(rms<.065);console.log('Robin sphere Bi',bi,'RMS',rms);}
assert.throws(()=>validate({...defaults(),across:NaN}));assert.throws(()=>validate({...defaults(),flipTimes:[10,9]}));console.log('PASS iPhone solver cross-platform, exact flips, equilibrium, sphere checks');
